name: 01 - Building Blocks

on: push

jobs:

  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello - world"

  good_bye:
    runs-on: ubuntu-latest
    steps:
      # First step fails initially
      - name: Failed step
        run: |
          echo "I will fail"
          exit 1

      - name: Say goodbye  # Second step
        run: echo "Goodbye"

      - name: Succeeding step (updated version)
        run: |
          echo "This will now succeed"
          exit 0
