name: 01 - Building Blocks

on: push

jobs:
 
  hello:

   runs-on: ubuntu latest

   steps:

    -run: echo "Hellow  -world"

good bye:

 runs-on: ubuntu-latest

 steps:

  # First step fails initally

  - name: Failed step # First step

    run: |

     echo "I will fail"

     exit 1

   - name: Say gooodbye  # Second step
   
     run: echo "Good bye"

    - name: Succeeding step (updated version) 
      run: |

        echo "This will now succeed"

        exit 0
        
     

 
